[package]
name = "sdock"
version = "0.1.0"
edition = "2021"

[dependencies]
libharuhishot =          { version = "0.4" }
wayland-client =         { version = "0.31" }
wayland-protocols =      { version = "0.32" }


tempfile = "3.2"

